version: '1.0.{build}'
image: Visual Studio 2017
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore
build_script:
  - cmd: dotnet build ./XKCD.Core/
clone_depth: 1
test_script:
  - cmd: dotnet test ./XKCD.Tests/
deploy: off
