language: csharp
mono: none
dist: bionic
dotnet: 2.2.105

script:
- dotnet restore
- dotnet build ./XKCD.Core/
- dotnet test ./XKCD.Tests/

notifications:
    email:
        on_success: never
        on_failure: always
